### ISSUE TITLE
cpanfile.snapshot module order problem

### ISSUE THREAD

**Issue by putaotao** [perl-carton/carton#185] opened 2014-10-22 09:56 UTC
$ mkdir a; cd a; echo "requires 'Business::ISBN', '2.09';" > cpanfile; carton install;
$ cd ..
$ mkdir b; cd b; cp -pr ../a/cpanfile ../a/cpanfile.snapshot .; carton install

then will report:
Installing modules using /home/xxx/b/cpanfile
Successfully installed ExtUtils-MakeMaker-6.98 (upgraded from 6.57_05)
Successfully installed Business-ISBN-Data-20140910.002
! Installing the dependencies failed: Module 'Business::ISBN' is not installed
! Bailing out the installation for /home/songxiaonan/tmp/1t/b/.
2 distributions installed
Installing modules failed

===============================================================

in "cpanfile.snapshot" file

if i move 

  Business-ISBN-2.09
    pathname: B/BD/BDFOY/Business-ISBN-2.09.tar.gz
    provides:
      Business::ISBN 2.09
      Business::ISBN10 2.09
      Business::ISBN13 2.09
    requirements:
      Business::ISBN::Data 20140910
      ExtUtils::MakeMaker 0
      URI 0

after 

  Business-ISBN-Data-20140910.002
    pathname: B/BD/BDFOY/Business-ISBN-Data-20140910.002.tar.gz
    provides:
      Business::ISBN 20140910.002
      Business::ISBN::Data 20140910.002
    requirements:
      Carp 0
      ExtUtils::MakeMaker 0
      File::Basename 0
      File::Spec::Functions 0

run "carton install" will work, but "cpanfile.snapshot" will change again

**Comment by bjakubski** [comment] 2015-12-15 13:34
Business::ISBN::Data in newest version is fixed and does not provide/index Business::ISBN, which fixes this issue.
Depending on how we treat such situation (that distribution provided erroneous package)  this possibly may be considered not a bug in carton

**Comment by miyagawa** [comment] 2015-12-16 01:38
Thanks for the update. Closing now.

**Closed by miyagawa** 2015-12-16 01:38 UTC
