### ISSUE TITLE
List::MoreUtils , carton install --deployment not working (XSLoader)

### ISSUE THREAD

**Issue by pierre-vigier** [perl-carton/carton#210] opened 2016-08-02 09:15 UTC
Hi,

i have a strange issue, with --deployment flag.

With the following cpanfile:

```perl
requires 'List::MoreUtils';
```

if i install that with `carton`, then delete the `cpanfile.snapshot` and then run `carton install --deployment`, i face the following error message:

```
[pierre:~/tmp/xs]> carton install --deployment
Installing modules using /Users/pierre.vigier/tmp/xs/cpanfile (deployment mode)
Found XSLoader  which doesn't satisfy 0.22.
Successfully installed Exporter-Tiny-0.042
! Installing the dependencies failed: Installed version (0.16) of XSLoader is not in range '0.22'
! Bailing out the installation for List-MoreUtils-0.416.
! Installing the dependencies failed: Module 'List::MoreUtils' is not installed
! Bailing out the installation for /Users/pierre.vigier/tmp/xs/.
1 distribution installed
Installing modules failed
```

The corresponding cpanfile.snapshot is generated by carton install

```
# carton snapshot format: version 1.0
DISTRIBUTIONS
  Exporter-Tiny-0.042
    pathname: T/TO/TOBYINK/Exporter-Tiny-0.042.tar.gz
    provides:
      Exporter::Shiny 0.042
      Exporter::Tiny 0.042
    requirements:
      ExtUtils::MakeMaker 6.17
      perl 5.006001
  List-MoreUtils-0.416
    pathname: R/RE/REHSACK/List-MoreUtils-0.416.tar.gz
    provides:
      List::MoreUtils 0.416
      List::MoreUtils::PP 0.416
      List::MoreUtils::XS 0.416
    requirements:
      Carp 0
      Exporter::Tiny 0.038
      ExtUtils::MakeMaker 0
      File::Basename 0
      File::Copy 0
      File::Path 0
      File::Spec 0
      IPC::Cmd 0
      XSLoader 0.22
      base 0
  XSLoader-0.22
    pathname: S/SA/SAPER/XSLoader-0.22.tar.gz
    provides:
      XSLoader undef
    requirements:
      ExtUtils::MakeMaker 0
      Test::More 0.47
```

Any ideas why the --deployment does not work there? seems to be related to the XSLoader-0.22 that does not specify the version of XSLoader it is providing

**Comment by skaji** [comment] 2016-08-02 14:11
## Problem

cpanm creates install.json for XSLoader with empty "provides".
```
> cat local/lib/perl5/darwin-2level/.meta/XSLoader-0.22/install.json
{"dist":"XSLoader-0.22","pathname":"S/SA/SAPER/XSLoader-0.22.tar.gz","name":"XSLoader","version":"0.22","provides":{},"target":"XSLoader"}
```

So cpanfile.snapshot has `XSLoader undef`
```
  XSLoader-0.22
    pathname: S/SA/SAPER/XSLoader-0.22.tar.gz
    provides:
      XSLoader undef
```

## Why cpanm creates install.json with empty "provides"

1. First cpanm configures XSLoader
2. During configuration, XSLoader.pm is removed. https://metacpan.org/source/SAPER/XSLoader-0.22/Makefile.PL#L62
3. Then cpanm try to extract "provides" for XSLoader. However XSLoader_pm.PL is skipped, so cpanm does not extract any "provides". https://github.com/miyagawa/cpanminus/blob/devel/lib/App/cpanminus/script.pm#L2464

## Solutions

### (a) Extract provides *before* configuration

```diff
diff --git lib/App/cpanminus/script.pm lib/App/cpanminus/script.pm
index 7873c16..869c29c 100644
--- lib/App/cpanminus/script.pm
+++ lib/App/cpanminus/script.pm
@@ -2188,15 +2188,15 @@ sub build_stuff {
           or return;
     }

+    if ($dist->{cpanmeta} && $dist->{source} eq 'cpan') {
+        $dist->{provides} = $dist->{cpanmeta}{provides} || $self->extract_packages($dist->{cpanmeta}, ".");
+    }
+
     $self->diag_progress("Configuring $target");

     my $configure_state = $self->configure_this($dist, $depth);
     $self->diag_ok($configure_state->{configured_ok} ? "OK" : "N/A");

-    if ($dist->{cpanmeta} && $dist->{source} eq 'cpan') {
-        $dist->{provides} = $dist->{cpanmeta}{provides} || $self->extract_packages($dist->{cpanmeta}, ".");
-    }
-
     # install direct 'test' dependencies for --installdeps, even with --notest
     my $root_target = (($self->{installdeps} or $self->{showdeps}) and $depth == 0);
     $dist->{want_phases} = $self->{notest} && !$root_target
```

### (b) Accept `_pm.PL` file
```diff
diff --git lib/App/cpanminus/script.pm lib/App/cpanminus/script.pm
index 7873c16..cabfda2 100644
--- lib/App/cpanminus/script.pm
+++ lib/App/cpanminus/script.pm
@@ -2461,7 +2461,7 @@ sub extract_packages {

     require Parse::PMFile;

-    my @files = grep { /\.pm(?:\.PL)?$/ && $try->($_) } $self->list_files;
+    my @files = grep { /[._]pm(?:\.PL)?$/ && $try->($_) } $self->list_files;

     my $provides = { };

```

**Comment by polettix** [comment] 2016-08-03 14:58
I hit the same issue right now. Just by gut feeling, I'd say the second approach is less invasive. BUT.

The lack of `provides` (it's a shame this key is optional!) gives raise to all this cinema. [This can trick PAUSE too](http://www.dagolden.com/index.php/2419/how-to-add-provides-metadata-via-makefile-pl/) in the general case, but not this time as the distribution is in CPAN. So I wonder:

- how did PAUSE figure this out?
- is it possible to reuse the same trick here?

This might lead us to 1, 2 or to some 3rd option.

**Comment by miyagawa** [comment] 2016-08-03 16:45
PAUSE scans before running configure (well PAUSE does not run configure at all) for indexing purposes.

cpanm used to scan `blib` after running configure && build, to make sure indexing what's going to be installed because what it wanted was an "installation database" and not "which dist owns which package" list. That's where the mismatch comes from. Carton uses the cpanm installation data because the purpose is to recreate installed modules, so what's going to be installed is more important, but frankly, just because that's what cpanm does.

cpanm used to look for `blib` to scan, but it might not be done that way anymore, so it might make sense to move it to pre-configure, but then there's a possibility of configure scripts generating the `provides` fields and adding them to MYMETA.json.

So ugh, the ideal would be that XSLoader dist having the proper `provides` field.

**Comment by skaji** [comment] 2016-08-03 16:56
> So ugh, the ideal would be that XSLoader dist having the proper provides field.

Indeed:)

**Comment by polettix** [comment] 2016-08-04 07:16
> it might make sense to move it to pre-configure, but then there's a possibility of configure scripts generating the `provides` fields and adding them to MYMETA.json.

Result: what's good for PAUSE is not good for us here. Ouch!

> So ugh, the ideal would be that XSLoader dist having the proper `provides` field.

I wonder what would be best:

- @maddingue might follow @xdg's suggestion [here](http://www.dagolden.com/index.php/2419/how-to-add-provides-metadata-via-makefile-pl/) and solve this specific issue;
- @bingos might extend `ExtUtils::MakeMaker` to generate `provides` automatically, solving a wider class of issues.

All of the above might also be addressed with pull requests where others propose patches of course. Let's see if they can be lured in the conversation...

**Comment by pierre-vigier** [comment] 2016-08-04 10:23
Meanwhile, i created a ticket there:
https://rt.perl.org/Ticket/Display.html?id=128836

**Comment by melo** [comment] 2016-08-04 17:26
Just got hit with this...

Created this miyagawa/cpanminus#511, that uses option b) from @skaji above, although my regexp is more complex because I don't want to match `.pm.PL`, not sure if it is worth the trouble.

Note to self: scan Carton issues before going down this rabbit hole...

**Comment by melo** [comment] 2016-08-04 17:30
I do agree that the proper fix is for XSLoader to provide the provides, but if `cpanm` is scanning `.pm` and it does support `.pm.PL`, then I don't see any problem about also supporting `_pm.PL`... I think it would be consistent.

**Comment by karenetheridge** [comment] 2016-08-04 20:29
> cpanm used to look for blib to scan

Why is it no longer doing this?  blib is the right place to look for files to be installed, not the root of the inflated tarball.

**Comment by miyagawa** [comment] 2016-08-04 21:24
https://github.com/miyagawa/cpanminus/commit/eee30eef2ebb514ef7163e85fb16eef6ba1ef309 is the commit

I forgot the reason but scanning blib also had issues because some packages do not build the artifacts into that directory (FCGI.pm is one example) and I decided to do a PAUSE way.

**Comment by miyagawa** [comment] 2016-08-05 07:51
@melo `.pm.PL` is completely fine to match, @skaji's regexp though would match `Foo_pm` so yours is definitely better.

**Comment by miyagawa** [comment] 2016-08-05 08:00
so the actual problem is that cpanm now scans packages between configure & build.

* Before configure: Static list of packages (PAUSE does here)
* After configure: use MYMETA (current cpanm does here)
* After build: MYMETA + look for blib (old cpanm used to do here)

The problem with XSLoader is that its configure script https://metacpan.org/source/SAPER/XSLoader-0.22/Makefile.PL#L62 deletes `XSLoader.pm` in the distribution, and then `make` will recreate it via MakeMaker 😢

**Comment by miyagawa** [comment] 2016-08-05 08:09
@karenetheridge putting files to `blib` is never a documented practice, and it cannot be the "right" way to extract packages. It will definitely work for 99% of the case, but cannot handle the rest 1%, and doing the PAUSE way is the only way to make sure we get the same data..

**Comment by melo** [comment] 2016-08-05 09:20
Doing it "the PAUSE way" has the added advantage of being consistent inside the ecosystem.

Can we move forward with matching _pm.PL?

**Comment by polettix** [comment] 2016-08-05 10:19
I agree that "the PAUSE way" is how things should be done.

`cpanm` (and `carton` as a consequence) is *not* doing it "the PAUSE way" at the moment, [according to this comment](https://github.com/perl-carton/carton/issues/210#issuecomment-237782283). Hence, any move must be done very carefully or there's the risk of a [left-pad nightmare](http://blog.npmjs.org/post/141577284765/kik-left-pad-and-npm).

Widening the scope of the match goes in the other direction actually, i.e. extending the heuristic and doing things differently from PAUSE. This is an effective workaround and I'd like to see it in the main `cpanm`/`carton` while a decision is taken.

**Comment by miyagawa** [comment] 2016-08-05 14:39
> Can we move forward with matching _pm.PL?

Well, No, if we aim for the PAUSE compatibilities, matching _pm.PL isn't the answer. PAUSE scans packages in pre-configure, at that point the stub `XSLoader.pm` still exists and packages can be extracted from there. 

@skaji's a) is the PAUSE compatible option. I still do not like it 100% because that way the package list is not always the same with what's installed - doing it after build by combining MYMETA's provides and `blib` is the right option for that.

**Comment by miyagawa** [comment] 2016-08-05 14:45
out of curiosity - is this new in XSLoader 0.22?

**Comment by skaji** [comment] 2016-08-05 14:55
No, it isn't.
http://cpanmetadb.plackperl.org/v1.0/history/XSLoader
```
> for v in 0.15 0.16 0.20 0.22; do cpanm -nq --reinstall -llocal$v XSLoader@$v; cat local$v/lib/perl5/darwin-2level/.meta/XSLoader-$v/install.json; echo ""; done
Successfully installed XSLoader-0.15 (downgraded from 0.22)
1 distribution installed
{"dist":"XSLoader-0.15","version":"0.15","pathname":"S/SA/SAPER/XSLoader-0.15.tar.gz","provides":{},"target":"XSLoader","name":"XSLoader"}
Successfully installed XSLoader-0.16 (downgraded from 0.22)
1 distribution installed
{"name":"XSLoader","provides":{},"target":"XSLoader","pathname":"S/SA/SAPER/XSLoader-0.16.tar.gz","version":"0.16","dist":"XSLoader-0.16"}
Successfully installed XSLoader-0.20 (downgraded from 0.22)
1 distribution installed
{"target":"XSLoader","version":"0.20","pathname":"S/SA/SAPER/XSLoader-0.20.tar.gz","provides":{},"dist":"XSLoader-0.20","name":"XSLoader"}
Successfully reinstalled XSLoader-0.22
1 distribution installed
{"target":"XSLoader","version":"0.22","provides":{},"name":"XSLoader","dist":"XSLoader-0.22","pathname":"S/SA/SAPER/XSLoader-0.22.tar.gz"}
```

**Comment by miyagawa** [comment] 2016-08-05 14:56
right, I guess this has not been an issue effectively because XSLoader is a core module.

**Comment by karenetheridge** [comment] 2016-08-05 17:22
I prepared a patch for XSLoader in https://rt.perl.org/Ticket/Display.html?id=128836.

**Comment by miyagawa** [comment] 2016-08-05 17:26
Thanks @karenetheridge, i know it is not a bug in XSLoader per se, but that'd help mitigate this specific situation.

**Comment by maddingue** [comment] 2016-08-13 23:42
Sorry, I just discovered that I have been mentioned in this ticket.

@miyagawa wrote:
> The problem with XSLoader is that its configure script https://metacpan.org/source/SAPER/XSLoader-0.22/Makefile.PL#L62 deletes XSLoader.pm in the distribution, and then make will recreate it via MakeMaker 😢

> out of curiosity - is this new in XSLoader 0.22?

For the records, this stub `XSLoader.pm` is present since the very first CPAN release: it is only here so that PAUSE has a `.pm` file to parse the version from. This is why it is deleted by `Makefile.PL`, to make sure that `XSLoader_pm.PL` is executed and create a `XSLoader.pm` suited for the local Perl. I guess it should be possible to delete the `.pm`file at build stage, just before the `.PL` file is executed.

In the mean time, I'll apply the patch made by @karenetheridge and make a new CPAN release.

**Comment by melo** [comment] 2016-08-16 15:34
Hi @maddingue,

thanks! Any idea when the new XSLoader will be on CPAN? I'm using a patched Carton to work around this.

Can I help with anything?

Thanks,

**Comment by dracos** [comment] 2016-08-26 11:04
As a workaround, in case anyone else looks at this, I've just patched our `cpanfile.snapshot` so that it has a working provides line for XSLoader.

**Comment by maddingue** [comment] 2016-08-31 17:05
Sorry, I knew I had forgotten something. XSLoader 0.23 uploaded on the CPAN.

**Comment by skaji** [comment] 2016-08-31 23:43
@maddingue 
XSLoader-0.23's META.json states XSLoader version = 0.20. 
https://metacpan.org/source/SAPER/XSLoader-0.23/META.json#L42

So it seems that the latest release for XSLoader is still XSLoader-0.22.
```
> TZ=UTC date
Wed Aug 31 23:42:18 UTC 2016
> curl -s www.cpan.org/modules/02packages.details.txt.gz | gunzip --stdout| grep '^XSLoader'
XSLoader                           0.22  S/SA/SAPER/XSLoader-0.22.tar.gz
```

**Comment by maddingue** [comment] 2016-09-01 12:45
Ah, I see. I hadn't reviewed the patch because I assumed it has already been. Now I see there's a mistake: it uses `${$PACKAGE.'::VERSION'}`, which is the currently installed version of `XSLoader`, not the one about to be installed.

An easy fix could have been to set `version` to `'$(VERSION)'`, so it uses the version number parsed by `ExtUtils::MakeMaker`, however, this doesn't work. I'm looking for alternative solutions.

**Comment by maddingue** [comment] 2016-09-01 13:05
Fixed using `ExtUtils::MM_Unix->parse_version()`.
XSLoader 0.24 uploaded on the CPAN.
» https://metacpan.org/source/SAPER/XSLoader-0.24/META.yml

**Comment by melo** [comment] 2016-09-01 15:03
I've just tested and this is fixed now.

Used this `cpanfile`:

```
requires 'XSLoader', '== 0.22';
requires 'List::MoreUtils';
```

Running `rm -rf local ; carton install ; rm -rf local ; carton install --deployment` fails.

After updating the `cpanfile` to use `0.24`, the same command works.

Thanks @maddingue!

**Comment by pierre-vigier** [comment] 2016-09-02 01:47
Thank you all, it's working like a charm now!

**Closed** 2016-09-02 01:48 UTC
