### ISSUE TITLE
Can't locate Menlo/CLI/Compat.pm in @INC

### ISSUE THREAD

**Issue by dex4er** [perl-carton/carton#237] opened 2018-05-03 11:49 UTC
Hi.

```
carton
carton bundle
carton fatpack
vendor/bin/carton install --deployment --cached
```

```
Installing modules using /builds/dex4er/cpanfile (deployment mode)
Can't locate Menlo/CLI/Compat.pm in @INC (you may need to install the Menlo::CLI::Compat module) (@INC contains: FatPacked::93920372684040=HASH(0x556b8a737508) /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at vendor/bin/carton line 2740.
```

Worked with previous version: v1.0.28

**Comment by miyagawa** [comment] 2018-05-03 15:36
what version of Carton and Menlo are you using?

**Comment by miyagawa** [comment] 2018-05-03 17:52
This should be fixed in 1.0.31. If not, please reopen with more details.

**Comment by dex4er** [comment] 2018-05-03 22:46
More detailed log from my CI:

```
+ curl -k -L cpanmin.us
+ perl - App::cpanminus
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  295k  100  295k    0     0   929k      0 --:--:-- --:--:-- --:--:--  932k
--> Working on App::cpanminus
Fetching http://www.cpan.org/authors/id/M/MI/MIYAGAWA/App-cpanminus-1.7044.tar.gz ... OK
Configuring App-cpanminus-1.7044 ... OK
Building and testing App-cpanminus-1.7044 ... OK
Successfully installed App-cpanminus-1.7044
1 distribution installed
+ cpanm -n App::FatPacker Carton ExtUtils::MakeMaker File::pushd Menlo::Legacy Socket Try::Tiny
--> Working on App::FatPacker
Fetching http://www.cpan.org/authors/id/M/MS/MSTROUT/App-FatPacker-0.010007.tar.gz ... OK
Configuring App-FatPacker-0.010007 ... OK
Building App-FatPacker-0.010007 ... OK
Successfully installed App-FatPacker-0.010007
--> Working on Carton
Fetching http://www.cpan.org/authors/id/M/MI/MIYAGAWA/Carton-v1.0.31.tar.gz ... OK
Configuring Carton-v1.0.31 ... OK
==> Found dependencies: Class::Tiny, Try::Tiny, Menlo::CLI::Compat, Path::Tiny, Module::CPANfile
--> Working on Class::Tiny
Fetching http://www.cpan.org/authors/id/D/DA/DAGOLDEN/Class-Tiny-1.006.tar.gz ... OK
Configuring Class-Tiny-1.006 ... OK
Building Class-Tiny-1.006 ... OK
Successfully installed Class-Tiny-1.006
--> Working on Try::Tiny
Fetching http://www.cpan.org/authors/id/E/ET/ETHER/Try-Tiny-0.30.tar.gz ... OK
Configuring Try-Tiny-0.30 ... OK
Building Try-Tiny-0.30 ... OK
Successfully installed Try-Tiny-0.30
--> Working on Menlo::CLI::Compat
Fetching http://www.cpan.org/authors/id/M/MI/MIYAGAWA/Menlo-Legacy-1.9021.tar.gz ... OK
Configuring Menlo-Legacy-1.9021 ... OK
==> Found dependencies: Menlo
--> Working on Menlo
Fetching http://www.cpan.org/authors/id/M/MI/MIYAGAWA/Menlo-1.9019.tar.gz ... OK
Configuring Menlo-1.9019 ... OK
==> Found dependencies: CPAN::DistnameInfo, URI, Capture::Tiny, File::pushd, HTTP::Tinyish, String::ShellQuote, CPAN::Meta::Check, File::Which, Parse::PMFile, CPAN::Common::Index, Module::CPANfile, ExtUtils::InstallPaths, ExtUtils::Helpers, ExtUtils::Config, Win32::ShellQuote
--> Working on CPAN::DistnameInfo
Fetching http://www.cpan.org/authors/id/G/GB/GBARR/CPAN-DistnameInfo-0.12.tar.gz ... OK
Configuring CPAN-DistnameInfo-0.12 ... OK
Building CPAN-DistnameInfo-0.12 ... OK
Successfully installed CPAN-DistnameInfo-0.12
--> Working on URI
Fetching http://www.cpan.org/authors/id/E/ET/ETHER/URI-1.74.tar.gz ... OK
Configuring URI-1.74 ... OK
Building URI-1.74 ... OK
Successfully installed URI-1.74
--> Working on Capture::Tiny
Fetching http://www.cpan.org/authors/id/D/DA/DAGOLDEN/Capture-Tiny-0.48.tar.gz ... OK
Configuring Capture-Tiny-0.48 ... OK
Building Capture-Tiny-0.48 ... OK
Successfully installed Capture-Tiny-0.48
--> Working on File::pushd
Fetching http://www.cpan.org/authors/id/D/DA/DAGOLDEN/File-pushd-1.014.tar.gz ... OK
Configuring File-pushd-1.014 ... OK
Building File-pushd-1.014 ... OK
Successfully installed File-pushd-1.014
--> Working on HTTP::Tinyish
Fetching http://www.cpan.org/authors/id/M/MI/MIYAGAWA/HTTP-Tinyish-0.14.tar.gz ... OK
Configuring HTTP-Tinyish-0.14 ... OK
==> Found dependencies: File::Which, IPC::Run3
--> Working on File::Which
Fetching http://www.cpan.org/authors/id/P/PL/PLICEASE/File-Which-1.22.tar.gz ... OK
Configuring File-Which-1.22 ... OK
Building File-Which-1.22 ... OK
Successfully installed File-Which-1.22
--> Working on IPC::Run3
Fetching http://www.cpan.org/authors/id/R/RJ/RJBS/IPC-Run3-0.048.tar.gz ... OK
Configuring IPC-Run3-0.048 ... OK
Building IPC-Run3-0.048 ... OK
Successfully installed IPC-Run3-0.048
Building HTTP-Tinyish-0.14 ... OK
Successfully installed HTTP-Tinyish-0.14
--> Working on String::ShellQuote
Fetching http://www.cpan.org/authors/id/R/RO/ROSCH/String-ShellQuote-1.04.tar.gz ... OK
Configuring String-ShellQuote-1.04 ... OK
Building String-ShellQuote-1.04 ... OK
Successfully installed String-ShellQuote-1.04
--> Working on CPAN::Meta::Check
Fetching http://www.cpan.org/authors/id/L/LE/LEONT/CPAN-Meta-Check-0.014.tar.gz ... OK
Configuring CPAN-Meta-Check-0.014 ... OK
Building CPAN-Meta-Check-0.014 ... OK
Successfully installed CPAN-Meta-Check-0.014
--> Working on Parse::PMFile
Fetching http://www.cpan.org/authors/id/I/IS/ISHIGAKI/Parse-PMFile-0.41.tar.gz ... OK
==> Found dependencies: ExtUtils::MakeMaker::CPANfile
--> Working on ExtUtils::MakeMaker::CPANfile
Fetching http://www.cpan.org/authors/id/I/IS/ISHIGAKI/ExtUtils-MakeMaker-CPANfile-0.08.tar.gz ... OK
Configuring ExtUtils-MakeMaker-CPANfile-0.08 ... OK
==> Found dependencies: Module::CPANfile
--> Working on Module::CPANfile
Fetching http://www.cpan.org/authors/id/M/MI/MIYAGAWA/Module-CPANfile-1.1004.tar.gz ... OK
Configuring Module-CPANfile-1.1004 ... OK
Building Module-CPANfile-1.1004 ... OK
Successfully installed Module-CPANfile-1.1004
Building ExtUtils-MakeMaker-CPANfile-0.08 ... OK
Successfully installed ExtUtils-MakeMaker-CPANfile-0.08
Configuring Parse-PMFile-0.41 ... OK
Building Parse-PMFile-0.41 ... OK
Successfully installed Parse-PMFile-0.41
--> Working on CPAN::Common::Index
Fetching http://www.cpan.org/authors/id/D/DA/DAGOLDEN/CPAN-Common-Index-0.010.tar.gz ... OK
Configuring CPAN-Common-Index-0.010 ... OK
==> Found dependencies: Tie::Handle::SkipHeader
--> Working on Tie::Handle::SkipHeader
Fetching http://www.cpan.org/authors/id/D/DA/DAGOLDEN/Tie-Handle-Offset-0.004.tar.gz ... OK
Configuring Tie-Handle-Offset-0.004 ... OK
Building Tie-Handle-Offset-0.004 ... OK
Successfully installed Tie-Handle-Offset-0.004
Building CPAN-Common-Index-0.010 ... OK
Successfully installed CPAN-Common-Index-0.010
--> Working on ExtUtils::InstallPaths
Fetching http://www.cpan.org/authors/id/L/LE/LEONT/ExtUtils-InstallPaths-0.011.tar.gz ... OK
Configuring ExtUtils-InstallPaths-0.011 ... OK
==> Found dependencies: ExtUtils::Config
--> Working on ExtUtils::Config
Fetching http://www.cpan.org/authors/id/L/LE/LEONT/ExtUtils-Config-0.008.tar.gz ... OK
Configuring ExtUtils-Config-0.008 ... OK
Building ExtUtils-Config-0.008 ... OK
Successfully installed ExtUtils-Config-0.008
Building ExtUtils-InstallPaths-0.011 ... OK
Successfully installed ExtUtils-InstallPaths-0.011
--> Working on ExtUtils::Helpers
Fetching http://www.cpan.org/authors/id/L/LE/LEONT/ExtUtils-Helpers-0.026.tar.gz ... OK
Configuring ExtUtils-Helpers-0.026 ... OK
Building ExtUtils-Helpers-0.026 ... OK
Successfully installed ExtUtils-Helpers-0.026
--> Working on Win32::ShellQuote
Fetching http://www.cpan.org/authors/id/H/HA/HAARG/Win32-ShellQuote-0.003001.tar.gz ... OK
Configuring Win32-ShellQuote-0.003001 ... OK
Building Win32-ShellQuote-0.003001 ... OK
Successfully installed Win32-ShellQuote-0.003001
Building Menlo-1.9019 ... OK
Successfully installed Menlo-1.9019
Building Menlo-Legacy-1.9021 ... OK
Successfully installed Menlo-Legacy-1.9021
--> Working on Path::Tiny
Fetching http://www.cpan.org/authors/id/D/DA/DAGOLDEN/Path-Tiny-0.104.tar.gz ... OK
Configuring Path-Tiny-0.104 ... OK
Building Path-Tiny-0.104 ... OK
Successfully installed Path-Tiny-0.104
Building Carton-v1.0.31 ... OK
Successfully installed Carton-v1.0.31
--> Working on ExtUtils::MakeMaker
Fetching http://www.cpan.org/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-7.34.tar.gz ... OK
Configuring ExtUtils-MakeMaker-7.34 ... OK
Building ExtUtils-MakeMaker-7.34 ... OK
Successfully installed ExtUtils-MakeMaker-7.34 (upgraded from 7.10_02)
--> Working on Socket
Fetching http://www.cpan.org/authors/id/P/PE/PEVANS/Socket-2.027.tar.gz ... OK
Configuring Socket-2.027 ... OK
Building Socket-2.027 ... OK
Successfully installed Socket-2.027 (upgraded from 2.020_03)
27 distributions installed
Installing modules using /builds/cpanfile
Successfully installed Config-Simple-4.58
Successfully installed File-Slurp-9999.19
Successfully installed Canary-Stability-2011
Successfully installed common-sense-3.74
Successfully installed Types-Serialiser-1.0
Successfully installed JSON-XS-3.02
Successfully installed NetAddr-IP-4.079
Successfully installed Data-Validate-IP-0.26
Successfully installed DBI-1.636
Successfully installed Net-Netmask-1.9022
Successfully installed IPC-Run3-0.048
Successfully installed Probe-Perl-0.03
Successfully installed Test-Script-1.12
Successfully installed DBD-mysql-4.035
Successfully installed ExtUtils-Config-0.008
Successfully installed ExtUtils-Helpers-0.022
Successfully installed ExtUtils-InstallPaths-0.011
Successfully installed Module-Build-Tiny-0.039
Successfully installed Readonly-2.05
19 distributions installed
Complete! Modules were installed into /builds/local
Copying M/ML/MLEHMANN/Canary-Stability-2011.tar.gz
Copying S/SH/SHERZODR/Config-Simple-4.58.tar.gz
Copying M/MI/MICHIELB/DBD-mysql-4.035.tar.gz
Copying T/TI/TIMB/DBI-1.636.tar.gz
Copying D/DR/DROLSKY/Data-Validate-IP-0.26.tar.gz
Copying L/LE/LEONT/ExtUtils-Config-0.008.tar.gz
Copying L/LE/LEONT/ExtUtils-Helpers-0.022.tar.gz
Copying L/LE/LEONT/ExtUtils-InstallPaths-0.011.tar.gz
Copying U/UR/URI/File-Slurp-9999.19.tar.gz
Copying R/RJ/RJBS/IPC-Run3-0.048.tar.gz
Copying M/ML/MLEHMANN/JSON-XS-3.02.tar.gz
Copying L/LE/LEONT/Module-Build-Tiny-0.039.tar.gz
Copying M/MU/MUIR/modules/Net-Netmask-1.9022.tar.gz
Copying M/MI/MIKER/NetAddr-IP-4.079.tar.gz
Copying K/KW/KWILLIAMS/Probe-Perl-0.03.tar.gz
Copying S/SA/SANKO/Readonly-2.05.tar.gz
Copying P/PL/PLICEASE/Test-Script-1.12.tar.gz
Copying M/ML/MLEHMANN/Types-Serialiser-1.0.tar.gz
Copying M/ML/MLEHMANN/common-sense-3.74.tar.gz
Bundling modules using /builds/cpanfile
Complete! Modules were bundled into /builds/vendor/cache
/tmp/CCtLDWUBiW/carton.pre.pl syntax OK
Bundling /builds/vendor/bin/carton
+ perl -Mlocal::lib=--deactivate-all
+ eval PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"; export PATH; unset PERL5LIB; unset PERL_LOCAL_LIB_ROOT; unset PERL_MB_OPT; unset PERL_MM_OPT;
+ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ export PATH
+ unset PERL5LIB
+ unset PERL_LOCAL_LIB_ROOT
+ unset PERL_MB_OPT
+ unset PERL_MM_OPT
+ rm -rf local
Installing modules using /builds/cpanfile (deployment mode)
Can't locate Menlo/CLI/Compat.pm in @INC (you may need to install the Menlo::CLI::Compat module) (@INC contains: FatPacked::93920372684040=HASH(0x556b8a737508) /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at vendor/bin/carton line 2740.
E
```

It works that way that on fresh Debian stretch Carton prepares bundle and then install it in offline mode.

So it fails with Carton v1.0.31

**Comment by dex4er** [comment] 2018-05-03 22:48
@miyagawa I can't reopen it and I don't want to create new issue for the same thing...

**Comment by miyagawa** [comment] 2018-05-03 22:58
I can't reproduce it, the carton fatpack is created with `Menlo/CLI/Compat.pm` correctly.

**Comment by dex4er** [comment] 2018-05-04 08:47
Give me some time, I'll reproduce it in Travis in separate repository with some demo project.

**Comment by dex4er** [comment] 2018-05-09 14:44
Ok:

The project is https://github.com/dex4er/example-carton

vendor-make/install scripts additionally upacks/repacks tarballs: it is for better versioning of vendor modules in git repository (but it is not important for this test; I used it for my dev environment)

The latest Carton 1.0.33 breaks https://travis-ci.org/dex4er/example-carton/builds/376861493
Previous run was correct: https://travis-ci.org/dex4er/example-carton/builds/376850549

**Comment by dex4er** [comment] 2018-05-09 16:42
I simplified this example and now there is one testing script:

https://github.com/dex4er/example-carton/blob/simple/.ci/before_script.sh

It should be run on clean Debian system

**Comment by nigelm** [comment] 2018-06-12 14:45
I am seeing this as well with Carton 1.033

The only Menlo packages in the fatpacked carton are:-

    package Menlo;
    package Menlo::Builder::Static;
    package Menlo::Dependency;
    package Menlo::Index::MetaCPAN;
    package Menlo::Index::MetaDB;
    package Menlo::Index::Mirror;
    package Menlo::Util;

**Comment by mschout** [comment] 2018-06-27 17:10
I'm also seeing this.  perl 5.26.2 in Docker image perl:5.26

**Comment by mschout** [comment] 2018-06-27 17:33
FWIW, carton 1.0.28 works.  1.0.29 and later have this problem it seems.  I note that 1.0.28 doesn't use Menlo.  I suspect the problem is upstream.

**Comment by miyagawa** [comment] 2018-06-27 17:35
it's not really upstream since fatpacking specifies all dists to be manually included. the problem should be in Carton's fatpacking code, but i cannot reproduce.

**Comment by mschout** [comment] 2018-06-27 18:12
From my debugging, what I'm seeing is that Packer.pm *does* include ```Menlo::CLI::Compat``` in the list of required modules, but the results of ```App::FatPacker->new->trace(...)``` does not include it.  This is why I think its upstream.  The FatPacker list should have included ```Menlo/CLI/Compat.pm``` but it does not.  I added this in ```Carton::Packer``` right after the ```$packer->trace()''' call:

```
warn "REQUIRED\n";
warn Dumper([sort $self->required_modules]);
warn "FatPacker:\n";
warn Dumper([sort @modules]);
```

And then running ```carton fatpack```  I see:

```
REQUIRED:
...
            'HTTP::Tinyish',
            'Menlo::CLI::Compat',
            'parent',
...
FatPack:
...
          'List/Util.pm',
          'Menlo.pm',
          'Menlo/Dependency.pm',
          'Menlo/Util.pm',
          'Module/CPANfile.pm',
...
```

Manually pushing ```Menlo/CLI/Compat.pm``` onto the ```@modules``` list fixes the problem, but the real issue is that FatPacker did not include it in the list.

**Comment by shadowcat-mst** [comment] 2018-06-27 19:01
Turns out this works better if the "require version::vpp;" doesn't fail, and App::FatPacker::Trace currently just does

    eval "use $_" for @extras;

so if you've put menlo in the extras list that would explain the problem.

I think something needs to make sure vpp.pm is around and also fatpacker shouldn't eat errors like that.

**Comment by mschout** [comment] 2018-06-27 19:11
@miyagawa what mst is referring to is that the Fatpack trace fails (at least for me) because of this block in ```Menlo::CLI::Compat``` around line 24.

```
if ($INC{"App/FatPacker/Trace.pm"}) {
    require version::vpp;
}
```

But ```version``` is not a prereq, so version::vpp isn't available because it doesn't get installed with Menlo::CLI::Compat.

**Comment by mschout** [comment] 2018-06-27 19:40
The final problem for me was that Menlo::Index::Mirror is lazy-loaded by Menlo::CLI::Compat, so FatPacker doesn't pick that one up.  I fixed that by pushing it onto the required list of modules by hand.  I'll send a PR for that.  And a PR to add a dependency on version.pm for Menlo::CLI::Compat.  After making those two changes, I get a working fatpacked carton once again.

**Comment by miyagawa** [comment] 2018-06-27 19:58
fatpacker should pack modules based on distributions, so as long as they belong to the same dist, not every module has to be explicitly loaded.

**Comment by mschout** [comment] 2018-06-27 20:00
Except that's not what it does.

All that App::FatPacker::Trace does is 

```
eval "use $module"
```

And then returns the list of everything that loaded successfully thats in %INC.

for each required module you give it.  If the module is lazy loaded via require inside a subroutine, it wont be picked up by FatPacker.

**Comment by mschout** [comment] 2018-06-27 20:04
So just to summarize, there are two known issues that cause ```carton bundle``` to fail.

1: Lazy loaded modules from other dists are not picked up by FatPacker::Trace.  The PR referenced above fixes that by explicitly listing the lazy loaded module that we need (Menlo::Index::Mirror)

2: App::FatPacker::Trace swallows compile-time errors when requiring modules, so if a prereq is missing, the module that it tried to require will not load and you get not warning or error.  Menlo-Legacy needs version::vpp, but only if running under App::FatPacker::Trace.  But Menlo-Legacy doesn't have a PREREQ_PM for version::vpp (or version).   If version::vpp isn't installed, Menlo::CLI::Compat will not be bundled by FatPacker because FatPacker::Trace can not load it.

Both of these issues will result in an unusable fatpacked carton.

**Comment by mschout** [comment] 2018-06-27 20:08
Submitted https://github.com/miyagawa/cpanminus/pull/577 to address the requirement for version::vpp

**Comment by miyagawa** [comment] 2018-06-27 21:02
> And then returns the list of everything that loaded successfully thats in %INC.

Right, then after that doesn't it try to find a packlist file containing these files and try to assemble all modules with `packlists_containing()`?

**Comment by mschout** [comment] 2018-06-27 21:18
Yes, it does that, but it doesn't then try to "use" the extra modules that it copeies from the .packlists, which means it doesn't fatpack the dependencies of *THOSE* modules.

 So, without my PR explicitly requreing the lazy-loaded Menlo::Index::Mirror you get a fatpacked carton that includes Menlo::Index::Mirror's sources, but not the dependencies of Menlo::Index::Mirror.  So running the fatpacked carton then fails (for me), because the fatpacked binary doesn't contain Tie::Handle::SkipHeader, a direct dependency of Menlo::Index::Mirror.  Hope that clears things up.

**Comment by miyagawa** [comment] 2018-06-27 21:20
Got it, thanks for the explanation and debugging :)

**Closed** 2018-06-28 16:32 UTC

**Comment by mschout** [comment] 2018-07-19 12:51
What version of `Menlo` and `Menlo::Legacy` do you have?  Here's a run against pristine 5.26 in docker showing it working for me:

```
$ docker run --rm -it perl:5.26 bash
root@76be3ae3a296:~# cpanm -q --notest Carton App::FatPacker
Successfully installed Try-Tiny-0.30
Successfully installed Class-Tiny-1.006
Successfully installed Path-Tiny-0.106
Successfully installed Module-CPANfile-1.1004
Successfully installed Tie-Handle-Offset-0.004
Successfully installed URI-1.74
Successfully installed CPAN-DistnameInfo-0.12
Successfully installed CPAN-Common-Index-0.010
Successfully installed Win32-ShellQuote-0.003001
Successfully installed File-Which-1.22
Successfully installed File-pushd-1.016
Successfully installed ExtUtils-MakeMaker-CPANfile-0.08
Successfully installed Parse-PMFile-0.41
Successfully installed Capture-Tiny-0.48
Successfully installed IPC-Run3-0.048
Successfully installed HTTP-Tinyish-0.14
Successfully installed local-lib-2.000024
Successfully installed ExtUtils-Config-0.008
Successfully installed String-ShellQuote-1.04
Successfully installed ExtUtils-InstallPaths-0.012
Successfully installed ExtUtils-Helpers-0.026
Successfully installed CPAN-Meta-Check-0.014
Successfully installed Menlo-1.9019
Successfully installed Menlo-Legacy-1.9022
Successfully installed Carton-v1.0.34
Successfully installed App-FatPacker-0.010007
26 distributions installed
root@76be3ae3a296:~# touch cpanfile
root@76be3ae3a296:~# carton fatpack
Attempting to create directory /root/perl5
/tmp/6OJjqKIzfY/carton.pre.pl syntax OK
Bundling /root/vendor/bin/carton
root@76be3ae3a296:~# ./vendor/bin/carton 
Installing modules using /root/cpanfile
Complete! Modules were installed into /root/local
```

**Comment by nigelm** [comment] 2018-07-19 13:13
Ah - its `Menlo-Legacy` - I had version 1.9021, updating to 1.9022 made it work.

Might be worth adding that version as a Carton dependancy.

Sorry - had missed that I had only updated the Carton package to current and not the underlying Menlo's

**Comment by dracos** [comment] 2019-05-03 20:30
The above docker script may work as given, but Menlo::CLI::Compat is not installed in the fatpack and the script does not work in a fresh location, it only works because Menlo has been installed. ie.:

```
~ § docker run --rm -it perl:5.26 bash
root@3071ae434225:~# cpanm -q --notest Carton App::FatPacker
Successfully installed Try-Tiny-0.30
Successfully installed ExtUtils-Helpers-0.026
Successfully installed Class-Tiny-1.006
Successfully installed File-Which-1.23
Successfully installed Module-CPANfile-1.1004
Successfully installed ExtUtils-MakeMaker-CPANfile-0.09
Successfully installed Parse-PMFile-0.41
Successfully installed ExtUtils-Config-0.008
Successfully installed CPAN-DistnameInfo-0.12
Successfully installed URI-1.76
Successfully installed Tie-Handle-Offset-0.004
Successfully installed CPAN-Common-Index-0.010
Successfully installed Capture-Tiny-0.48
Successfully installed String-ShellQuote-1.04
Successfully installed IPC-Run3-0.048
Successfully installed HTTP-Tinyish-0.15
Successfully installed CPAN-Meta-Check-0.014
Successfully installed Win32-ShellQuote-0.003001
Successfully installed local-lib-2.000024
Successfully installed File-pushd-1.016
Successfully installed ExtUtils-InstallPaths-0.012
Successfully installed Menlo-1.9019
Successfully installed Menlo-Legacy-1.9022
Successfully installed Path-Tiny-0.108
Successfully installed Carton-v1.0.34
Successfully installed App-FatPacker-0.010008
26 distributions installed
root@3071ae434225:~# touch cpanfile
root@3071ae434225:~# carton fatpack
Attempting to create directory /root/perl5
/tmp/gdYSNNgngh/carton.pre.pl syntax OK
Bundling /root/vendor/bin/carton
root@3071ae434225:~# ./vendor/bin/carton 
Installing modules using /root/cpanfile
Complete! Modules were installed into /root/local
root@3071ae434225:~# cpanm -U Menlo::Legacy
Menlo::Legacy contains the following files:

  /usr/local/lib/perl5/site_perl/5.26.3/Menlo/CLI/Compat.pm
  /usr/local/lib/perl5/site_perl/5.26.3/Menlo/Legacy.pm

Are you sure you want to uninstall Menlo::Legacy? [y] y

Unlink: /usr/local/lib/perl5/site_perl/5.26.3/Menlo/CLI/Compat.pm
Unlink: /usr/local/lib/perl5/site_perl/5.26.3/Menlo/Legacy.pm
Unlink: /usr/local/lib/perl5/site_perl/5.26.3/x86_64-linux-gnu/auto/Menlo/Legacy/.packlist

Successfully uninstalled Menlo::Legacy
root@3071ae434225:~# ./vendor/bin/carton 
Installing modules using /root/cpanfile
Can't locate Menlo/CLI/Compat.pm in @INC (you may need to install the Menlo::CLI::Compat module) (@INC contains: FatPacked::94305413377704=HASH(0x55c530aa2ea8) /usr/local/lib/perl5/site_perl/5.26.3/x86_64-linux-gnu /usr/local/lib/perl5/site_perl/5.26.3 /usr/local/lib/perl5/vendor_perl/5.26.3/x86_64-linux-gnu /usr/local/lib/perl5/vendor_perl/5.26.3 /usr/local/lib/perl5/5.26.3/x86_64-linux-gnu /usr/local/lib/perl5/5.26.3) at ./vendor/bin/carton line 2775.
```

**Comment by mschout** [comment] 2022-01-20 15:42
Fatpacked carton today again, and it still does not genreate a valid fatpack if `version::vpp` is not installed, so this still exists, and is fixed by the above MR.
